### 텐서 : 다차원 배열을 나타내는 자료형(넘파이의 ndarray)

<code>torch.tensor(data, dtype=None, device=None, requires_grad=False)</code>

- data : 텐서로 변환하고자 하는 데이터(파이썬 리스트, 넘파이 배열 등)
- dtype(optional) : 텐서의 데이터 타입, 기본값은 None, 자동으로 데이터 타입 인식
- device(optional) : 텐서가 사용될 디바이스, 기본값은 None, CPU 상에서 계산
- requires_grad(optional) : 해당 텐서가 그래디언트를 계산할지 여부, 기본값은 False

In [1]:
import torch

data = [[1,2,3], [4,5,6]]
print(data)

[[1, 2, 3], [4, 5, 6]]


In [2]:
x = torch.tensor(data)
y = torch.tensor(data, dtype=torch.float32)
print(x, "\n", y)

type(x)

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Tensor

### 1. 생성

In [3]:
import torch

# 1차원 텐서 생성
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [4]:
# 2차원 텐서 생성
y = torch.tensor([[1,2,3],[4,5,6]])
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# 모든 원소가 0인 3차원 텐서 생성
z = torch.zeros((2,3,4)) 
# 2 : 첫번째 차원의 크기 -> 2개의 3차원 행렬
# 3 : 두번째 차원의 크기 -> 3개의 행
# 4 : 세번째 차원의 크기 -> 4개의 열
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
# 모든 원소가 1인 4차원 텐서 생성
w = torch.ones((2,2,2,2))
print(w)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [7]:
# 랜덤한 값으로 채워진 3x3 텐서 생성
r = torch.rand((3,3))
print(r)

tensor([[0.6442, 0.2398, 0.7952],
        [0.9297, 0.6296, 0.0876],
        [0.0100, 0.2624, 0.0830]])


#### 분포에서 난수 생성
- rand : 균등분포(0,1)에서 난수 생성
- randn : 정규분포(0,1)에서 난수 생성

In [8]:
# 균등 분포(0,1)에서 난수를 생성
x = torch.rand(2,3)
print(x)

tensor([[0.0418, 0.4445, 0.6420],
        [0.4662, 0.4054, 0.8661]])


In [9]:
# 정규 분포(0,1)에서 난수를 생성
y = torch.randn(2,3)
print(y)

tensor([[ 0.1399,  0.2789, -0.9537],
        [-0.1286,  0.6568, -0.1738]])


#### 메모리 상에 할당된 임의의 값으로 초기화된 텐서를 생성

In [10]:
# .Tensor 예제1
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [11]:
# .empty 예제
b = torch.empty(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# .Tensor 예제2
c = torch.Tensor(2,3)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### .from_numpy()와 .tensor()의 차이
- .from_numpy() : NumPy 배열을 Pytorch Tensor로 변환<br>기존 NumPy 배열과 데이터를 공유 -> 반환된 Tensor를 수정하면 NumPy 배열도 수정(동일 위치 참조)
- .tensor() : NumPy 배열과 유사한 새로운 Pytorch Tensor를 생성<br>새로운 Tensor와 NumPy 배열은 데이터 공유 X -> Tensor를 수정해도 NumPy 배열은 변경X

In [28]:
import torch
import numpy as np

# NumPy 배열 생성
a_np = np.array([1,2,3])

# NumPy 배열을 Pytorch Tensor로 변환
a_tensor = torch.from_numpy(a_np)

# Tensor 수정
a_tensor[0] = -1

print(a_np)

[-1  2  3]


In [29]:
import torch
import numpy as np

# NumPy 배열 생성
a_np = np.array([1,2,3])

# NumPy 배열을 Pytorch Tensor로 변환
a_tensor = torch.tensor(a_np)

# Tensor 수정
a_tensor[0] = -1

print(a_np)

[1 2 3]


#### torch.randn : 정규 분포에서 무작위로 추출한 난수를 가지고 지정된 크기의 텐서를 생성
<code>torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor</code>
- *size : 생성하려는 텐서의 크기를 나타내는 가변 인수<br>
ex) torch.rand(3,4)는 3x4크기의 2차원 텐서 생성
- out(optional) : 결과를 저장할 출력 텐서, 기본값은 None
- dtype(optional) : 생성되는 텐서의 데이터 타입을 지정하는 인수, 기본값은 None
- layout(optional) : 생성되는 텐서의 레이아웃을 지정하는 인수, 기본값은 torch.strided
- device(optional) : 생성되는 텐서의 디바이스를 지정하는 인수, 기본값은 None, 현재 사용 중인 디바이스로 자동 설정
- requires_grad(optional) : 생성되는 텐서의 기울기를 계산할 지 여부를 지정하는 인수, 기본값은 False

In [31]:
import torch

# 2x3 크기의 텐서 생성
tensor = torch.randn(2, 3)

print(tensor)

tensor([[ 0.7808,  0.1828, -0.3606],
        [ 0.5665, -0.4726,  0.9861]])


### 2. 파이토치 텐서의 속성
<ul>
<li>데이터 타입(dtype)
<ul>
<li>torch.FloatTensor : 32비트 부동소수점 저장</li>
<li>torch.LongTensr : 64비트 정수를 저장</li>
</ul></li>
<li>디바이스(device) : 텐서가 저장되는 장치(CPU/GPU)</li>
<li>크기(size) : 텐서 안에 있는 데이터의 개수
<ul><li>torch.Size([3,4]) : 3행 4열의 행렬</li></ul></li>
<li>모양(shape) : 텐서의 차원</li>
</ul>

In [27]:
import torch

# 데이터 타입
x = torch.tensor([1,2,3])
print(x.dtype) # 기본값 : torch.int64(int의 경우), torch.float32(float의 경우)

# 디바이스
device = torch.device('cpu')
x = torch.tensor([1,2,3], device = device)
print(x.device) # CPU

# 크기
x = torch.tensor([1,2,3])
print(x.numel()) # .numel() : 크기 출력

# 모양
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x.shape, x.size())

# 모양 변경
x = torch.tensor([1,2,3,4])
y = x.view(2,2) # x.reshape(2,2)
print(y.size())

torch.int64
cpu
3
torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([2, 2])


### 3. 연산

In [33]:
import torch

# 텐서 생성
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a,b)
# 덧셈
c = a + b
print(c)

# 뺌셈
d = a - b
print(d)

# 곱셈
e = a * b
print(e)

# 나눗셈
f = a / b
print(f)

# 행렬곱
g = torch.mm(a,b)
print(g)

# 점곱
h = torch.dot(torch.tensor([1,2]), torch.tensor([3,4])) # x^T * y
print(h)

tensor([[1, 2],
        [3, 4]]) tensor([[5, 6],
        [7, 8]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19, 22],
        [43, 50]])
tensor(11)


In [36]:
# 요소별 최대값 계산
i = torch.tensor([[1,2],[3,4]])
j = torch.tensor([[4,3],[2,1]])
k = torch.max(i, j)
print(k)

# 차원 축소
l = torch.tensor([[1,2],[3,4]])
m = torch.sum(l, dim=0)
print(m)

# 전치
n = torch.tensor([[1,2],[3,4]])
o = torch.transpose(n, 0, 1)
print(o)

tensor([[4, 3],
        [3, 4]])
tensor([4, 6])
tensor([[1, 3],
        [2, 4]])


In [38]:
# 인덱싱
p = torch.tensor([[1,2],[3,4],[5,6]])
q = p[1,0]
print(q)

# 슬라이싱
r = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
s = r[:, :2]
print(s)

# 조건부 인덱싱
t = torch.tensor([1,2,3,4,5])
u = t[t > 3]
print(u)

tensor(3)
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([4, 5])


#### 텐서의 차원을 변경하는 연산
- unsqueeze() : 지정된 차원에 1인 차원 추가
- squeeze() : 크기가 1인 차원 제거
- reshape() : 텐서의 형태 변환
- sort() : 텐서의 요소 정렬, 정렬된 텐서와 원래 인덱스 반환
- argsort() : 텐서의 요소를 정렬했을 때의 인덱스를 반환

In [49]:
import torch

# 텐서 생성
x = torch.tensor([1,2,3,4])
print(x, x.shape)

# 텐서 차원 변경
y = x.unsqueeze(0) # 첫 번째 차원에 1 추가
print(y, y.shape)

y = x.unsqueeze(1)
print(y, y.shape)

# 텐서 reshape
y = x.reshape(2,2)
print(y, y.shape)

# 텐서 정렬
x = torch.tensor([3,2,1])
y = torch.tensor([4,5,6])
z = torch.tensor([1,2,3])
a, b = torch.sort(x)
print(a, b)

a, b = torch.sort(y)
print(a, b)

a, b = torch.sort(z, descending = True)
print(a, b)

tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
tensor([1, 2, 3]) tensor([2, 1, 0])
tensor([4, 5, 6]) tensor([0, 1, 2])
tensor([3, 2, 1]) tensor([2, 1, 0])


#### 병합

In [54]:
# numpy
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1, "\n", arr2, "\n")
print(np.concatenate((arr1, arr2), axis=1))
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [56]:
# tensor
a1 = torch.tensor(arr1)
a2 = torch.tensor(arr2)
print(torch.cat((a1, a2), axis=1))
print(torch.vstack((a1,a2))) # 세로로 병합
print(torch.hstack((a1,a2))) # 가로로 병합

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


#### 유용한 함수들
<ul>
<li> torch.eq : 2개의 입력 텐서를 받아 같은 모양(shape)의 텐서를 반환<br>
두 텐서의 원소 간의 동등성을 비교하여 값(True/False)로 채워진 텐서를 반환</li>
<br>
<li> torch.softmax : 입력값을 확률 형태로 변환해주는 함수<br>
<code>torch.softmax(input, dim=None, dtype=None)</code></li>
<ul>
    <li>input : 소프트맥스 함수를 적용하려는 입력 텐서</li>
    <li>dim(optional) : 소프트맥스를 계산할 차원, 기본값은 None, 마지막 차원이 사용</li>
    <li>dtype(optional) : 출력 센서의 데이터타입, 기본값은 None</li>
</ul>
</ul>

In [60]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])
c = torch.tensor([1, 2, 4])

result1 = torch.eq(a, b)
result2 = torch.eq(a, c)

print(result1)
print(result2)

tensor([True, True, True])
tensor([ True,  True, False])


In [61]:
a = torch.tensor([1.0, 2.0, 3.0]) # 입력 텐서
softmax_output = torch.softmax(a, dim=0) # dim=0으로 소프트맥스 계산
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


#### 인플레이스 연산 : 원본 텐서의 값을 변경 -> 메모리를 절약
- add_
- sub_
- mul_
- div_
- pow_
- sqrt_
- round_
- floor_
- ceil_
- clamp_
- fill_

In [65]:
import torch

# 인플레이스 연산 예제
a = torch.tensor([1,2,3])
b = a # 동일한 메모리 주소 참조 -> 하나가 변경되면 나머지도 변경
a.add_(torch.tensor([1,1,1]))
print(a)
print(b)

tensor([2, 3, 4])
tensor([2, 3, 4])


- .fill_() : 텐서의 모든 요소를 지정된 값으로 새로운 텐서를 생성
- .full() : 주어진 크기와 지정된 값으로 새로운 텐서를 생성

In [66]:
import torch

# 3x3 크기의 텐서 생성
x = torch.zeros(3,3)
print(x)

# 모든 요소를 1로 채우기
x.fill_(1)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [67]:
import torch

# 3x3 크기의 텐서를 5로 채우기
x = torch.full((3,3), 5)
print(x)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
