### 텐서 : 다차원 배열을 나타내는 자료형(넘파이의 ndarray)

<code>torch.tensor(data, dtype=None, device=None, requires_grad=False)</code>

- data : 텐서로 변환하고자 하는 데이터(파이썬 리스트, 넘파이 배열 등)
- dtype(optional) : 텐서의 데이터 타입, 기본값은 None, 자동으로 데이터 타입 인식
- device(optional) : 텐서가 사용될 디바이스, 기본값은 None, CPU 상에서 계산
- requires_grad(optional) : 해당 텐서가 그래디언트를 계산할지 여부, 기본값은 False

In [1]:
import torch

data = [[1,2,3], [4,5,6]]
print(data)

[[1, 2, 3], [4, 5, 6]]


In [2]:
x = torch.tensor(data)
y = torch.tensor(data, dtype=torch.float32)
print(x, "\n", y)

type(x)

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Tensor

#### 1. 생성

In [3]:
import torch

# 1차원 텐서 생성
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [4]:
# 2차원 텐서 생성
y = torch.tensor([[1,2,3],[4,5,6]])
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# 모든 원소가 0인 3차원 텐서 생성
z = torch.zeros((2,3,4)) 
# 2 : 첫번째 차원의 크기 -> 2개의 3차원 행렬
# 3 : 두번째 차원의 크기 -> 3개의 행
# 4 : 세번째 차원의 크기 -> 4개의 열
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
# 모든 원소가 1인 4차원 텐서 생성
w = torch.ones((2,2,2,2))
print(w)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [7]:
# 랜덤한 값으로 채워진 3x3 텐서 생성
r = torch.rand((3,3))
print(r)

tensor([[0.6781, 0.8560, 0.1398],
        [0.7436, 0.3452, 0.5643],
        [0.7180, 0.2606, 0.6531]])


##### 분포에서 난수 생성
- rand : 균등분포(0,1)에서 난수 생성
- randn : 정규분포(0,1)에서 난수 생성

In [8]:
# 균등 분포(0,1)에서 난수를 생성
x = torch.rand(2,3)
print(x)

tensor([[0.4874, 0.7650, 0.0589],
        [0.9882, 0.6390, 0.6067]])


In [9]:
# 정규 분포(0,1)에서 난수를 생성
y = torch.randn(2,3)
print(y)

tensor([[-0.5322, -1.8572,  0.5014],
        [ 0.0211,  0.0680, -2.3845]])


##### 메모리 상에 할당된 임의의 값으로 초기화된 텐서를 생성

In [10]:
# .Tensor 예제1
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [11]:
# .empty 예제
b = torch.empty(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# .Tensor 예제2
c = torch.Tensor(2,3)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### .from_numpy()와 .tensor()의 차이
- .from_numpy() : NumPy 배열을 Pytorch Tensor로 변환<br>기존 NumPy 배열과 데이터를 공유 -> 반환된 Tensor를 수정하면 NumPy 배열도 수정(동일 위치 참조)
- .tensor() : NumPy 배열과 유사한 새로운 Pytorch Tensor를 생성<br>새로운 Tensor와 NumPy 배열은 데이터 공유 X -> Tensor를 수정해도 NumPy 배열은 변경X

In [13]:
import torch
import numpy as np

# NumPy 배열 생성
a_np = np.array([1,2,3])

# NumPy 배열을 Pytorch Tensor로 변환
a_tensor = torch.from_numpy(a_np)

# Tensor 수정
a_tensor[0] = -1

print(a_np)

[-1  2  3]


In [14]:
import torch
import numpy as np

# NumPy 배열 생성
a_np = np.array([1,2,3])

# NumPy 배열을 Pytorch Tensor로 변환
a_tensor = torch.tensor(a_np)

# Tensor 수정
a_tensor[0] = -1

print(a_np)

[1 2 3]


##### torch.randn : 정규 분포에서 무작위로 추출한 난수를 가지고 지정된 크기의 텐서를 생성
<code>torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor</code>
- *size : 생성하려는 텐서의 크기를 나타내는 가변 인수<br>
ex) torch.rand(3,4)는 3x4크기의 2차원 텐서 생성
- out(optional) : 결과를 저장할 출력 텐서, 기본값은 None
- dtype(optional) : 생성되는 텐서의 데이터 타입을 지정하는 인수, 기본값은 None
- layout(optional) : 생성되는 텐서의 레이아웃을 지정하는 인수, 기본값은 torch.strided
- device(optional) : 생성되는 텐서의 디바이스를 지정하는 인수, 기본값은 None, 현재 사용 중인 디바이스로 자동 설정
- requires_grad(optional) : 생성되는 텐서의 기울기를 계산할 지 여부를 지정하는 인수, 기본값은 False

In [15]:
import torch

# 2x3 크기의 텐서 생성
tensor = torch.randn(2, 3)

print(tensor)

tensor([[-1.6051, -0.0490,  1.1763],
        [ 0.0181, -0.4252,  0.4442]])


In [16]:
import torch

# 평균을 2, 표준편차를 1.5로 바꾸로 싶은 경우
mean = 2
std = 1.5
size = (3,4) # 원하는 사이즈 지정

# 평균이 2이고 표준 편차가 1.5인 정규분포에서 무작위로 샘플 생성
samples = torch.randn(size) * std + mean
print(samples)

tensor([[ 2.2179,  2.2671,  2.3802,  3.1352],
        [ 0.0160, -1.0280,  4.2760,  3.7700],
        [ 0.7445,  1.7273,  1.8676,  0.2182]])


#### 2. 파이토치 텐서의 속성
<ul>
<li>데이터 타입(dtype)
<ul>
<li>torch.FloatTensor : 32비트 부동소수점 저장</li>
<li>torch.LongTensr : 64비트 정수를 저장</li>
</ul></li>
<li>디바이스(device) : 텐서가 저장되는 장치(CPU/GPU)</li>
<li>크기(size) : 텐서 안에 있는 데이터의 개수
<ul><li>torch.Size([3,4]) : 3행 4열의 행렬</li></ul></li>
<li>모양(shape) : 텐서의 차원</li>
</ul>

In [17]:
import torch

# 데이터 타입
x = torch.tensor([1,2,3])
print(x.dtype) # 기본값 : torch.int64(int의 경우), torch.float32(float의 경우)

# 디바이스
device = torch.device('cpu')
x = torch.tensor([1,2,3], device = device)
print(x.device) # CPU

# 크기
x = torch.tensor([1,2,3])
print(x.numel()) # .numel() : 크기 출력

# 모양
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x.shape, x.size())

# 모양 변경
x = torch.tensor([1,2,3,4])
y = x.view(2,2) # x.reshape(2,2)
print(y.size())

torch.int64
cpu
3
torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([2, 2])


#### 3. 연산

In [18]:
import torch

# 텐서 생성
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a,b)
# 덧셈
c = a + b
print(c)

# 뺌셈
d = a - b
print(d)

# 곱셈
e = a * b
print(e)

# 나눗셈
f = a / b
print(f)

# 행렬곱
g = torch.mm(a,b)
print(g)

# 점곱
h = torch.dot(torch.tensor([1,2]), torch.tensor([3,4])) # x^T * y
print(h)

tensor([[1, 2],
        [3, 4]]) tensor([[5, 6],
        [7, 8]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19, 22],
        [43, 50]])
tensor(11)


In [19]:
# 요소별 최대값 계산
i = torch.tensor([[1,2],[3,4]])
j = torch.tensor([[4,3],[2,1]])
k = torch.max(i, j)
print(k)

# 차원 축소
l = torch.tensor([[1,2],[3,4]])
m = torch.sum(l, dim=0)
print(m)

# 전치
n = torch.tensor([[1,2],[3,4]])
o = torch.transpose(n, 0, 1)
print(o)

tensor([[4, 3],
        [3, 4]])
tensor([4, 6])
tensor([[1, 3],
        [2, 4]])


In [20]:
# 인덱싱
p = torch.tensor([[1,2],[3,4],[5,6]])
q = p[1,0]
print(q)

# 슬라이싱
r = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
s = r[:, :2]
print(s)

# 조건부 인덱싱
t = torch.tensor([1,2,3,4,5])
u = t[t > 3]
print(u)

tensor(3)
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([4, 5])


##### 텐서의 차원을 변경하는 연산
- unsqueeze() : 지정된 차원에 1인 차원 추가
- squeeze() : 크기가 1인 차원 제거
- reshape() : 텐서의 형태 변환
- sort() : 텐서의 요소 정렬, 정렬된 텐서와 원래 인덱스 반환
- argsort() : 텐서의 요소를 정렬했을 때의 인덱스를 반환

In [21]:
import torch

# 텐서 생성
x = torch.tensor([1,2,3,4])
print(x, x.shape)

# 텐서 차원 변경
y = x.unsqueeze(0) # 첫 번째 차원에 1 추가
print(y, y.shape)

y = x.unsqueeze(1)
print(y, y.shape)

# 텐서 reshape
y = x.reshape(2,2)
print(y, y.shape)

# 텐서 정렬
x = torch.tensor([3,2,1])
y = torch.tensor([4,5,6])
z = torch.tensor([1,2,3])
a, b = torch.sort(x)
print(a, b)

a, b = torch.sort(y)
print(a, b)

a, b = torch.sort(z, descending = True)
print(a, b)

tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])
tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
tensor([1, 2, 3]) tensor([2, 1, 0])
tensor([4, 5, 6]) tensor([0, 1, 2])
tensor([3, 2, 1]) tensor([2, 1, 0])


##### 병합

In [22]:
# numpy
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1, "\n", arr2, "\n")
print(np.concatenate((arr1, arr2), axis=1))
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# tensor
a1 = torch.tensor(arr1)
a2 = torch.tensor(arr2)
print(torch.cat((a1, a2), axis=1))
print(torch.vstack((a1,a2))) # 세로로 병합
print(torch.hstack((a1,a2))) # 가로로 병합

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


##### 유용한 함수들
<ul>
<li> torch.eq : 2개의 입력 텐서를 받아 같은 모양(shape)의 텐서를 반환<br>
두 텐서의 원소 간의 동등성을 비교하여 값(True/False)로 채워진 텐서를 반환</li>
<br>
<li> torch.softmax : 입력값을 확률 형태로 변환해주는 함수<br>
<code>torch.softmax(input, dim=None, dtype=None)</code></li>
<ul>
    <li>input : 소프트맥스 함수를 적용하려는 입력 텐서</li>
    <li>dim(optional) : 소프트맥스를 계산할 차원, 기본값은 None, 마지막 차원이 사용</li>
    <li>dtype(optional) : 출력 센서의 데이터타입, 기본값은 None</li>
</ul>
</ul>

In [24]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])
c = torch.tensor([1, 2, 4])

result1 = torch.eq(a, b)
result2 = torch.eq(a, c)

print(result1)
print(result2)

tensor([True, True, True])
tensor([ True,  True, False])


In [25]:
a = torch.tensor([1.0, 2.0, 3.0]) # 입력 텐서
softmax_output = torch.softmax(a, dim=0) # dim=0으로 소프트맥스 계산
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


##### 인플레이스 연산 : 원본 텐서의 값을 변경 -> 메모리를 절약
- add_
- sub_
- mul_
- div_
- pow_
- sqrt_
- round_
- floor_
- ceil_
- clamp_
- fill_

In [26]:
import torch

# 인플레이스 연산 예제
a = torch.tensor([1,2,3])
b = a # 동일한 메모리 주소 참조 -> 하나가 변경되면 나머지도 변경
a.add_(torch.tensor([1,1,1]))
print(a)
print(b)

tensor([2, 3, 4])
tensor([2, 3, 4])


- .fill_() : 텐서의 모든 요소를 지정된 값으로 새로운 텐서를 생성
- .full() : 주어진 크기와 지정된 값으로 새로운 텐서를 생성

In [27]:
import torch

# 3x3 크기의 텐서 생성
x = torch.zeros(3,3)
print(x)

# 모든 요소를 1로 채우기
x.fill_(1)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [28]:
import torch

# 3x3 크기의 텐서를 5로 채우기
x = torch.full((3,3), 5)
print(x)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### 실습

In [2]:
import torch
import numpy as np

# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print("GPU 사용")

In [3]:
# 텐서 초기화
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
# NumPy 배열로부터 생성
np_array = np.array(data)
print(np_array)

x_np = torch.from_numpy(np_array)
print(x_np)

y_np = torch.from_numpy(data) # data가 numpy가 아님

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


TypeError: expected np.ndarray (got list)

In [6]:
# 다른 텐서로부터 생성하기
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀
print(f"Ones Tensor : \n {x_rand} \n")


Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor : 
 tensor([[0.1298, 0.7463],
        [0.3321, 0.4177]]) 



In [7]:
# 무작위 또는 상수 값 사용
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0966, 0.1644, 0.5869],
        [0.6003, 0.4327, 0.1046]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# 텐서의 속성
tensor = torch.rand(3,4)

print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.4690, 0.6381, 0.2164, 0.6478],
        [0.4785, 0.6251, 0.0216, 0.5551],
        [0.6705, 0.8115, 0.8394, 0.8590]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [14]:
# 텐서 연산
tensor = torch.rand(4,4)
print(tensor, "\n")

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

tensor([[0.2240, 0.1235, 0.9753, 0.1161],
        [0.3348, 0.5936, 0.0995, 0.0501],
        [0.0473, 0.6618, 0.1144, 0.5100],
        [0.0258, 0.9578, 0.3849, 0.1836]]) 

First row: tensor([0.2240, 0.1235, 0.9753, 0.1161])
First column: tensor([0.2240, 0.3348, 0.0473, 0.0258])
Last column: tensor([0.1161, 0.0501, 0.5100, 0.1836])
tensor([[0.2240, 0.0000, 0.9753, 0.1161],
        [0.3348, 0.0000, 0.0995, 0.0501],
        [0.0473, 0.0000, 0.1144, 0.5100],
        [0.0258, 0.0000, 0.3849, 0.1836]])


In [17]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.2240, 0.0000, 0.9753, 0.1161, 0.2240, 0.0000, 0.9753, 0.1161, 0.2240,
         0.0000, 0.9753, 0.1161],
        [0.3348, 0.0000, 0.0995, 0.0501, 0.3348, 0.0000, 0.0995, 0.0501, 0.3348,
         0.0000, 0.0995, 0.0501],
        [0.0473, 0.0000, 0.1144, 0.5100, 0.0473, 0.0000, 0.1144, 0.5100, 0.0473,
         0.0000, 0.1144, 0.5100],
        [0.0258, 0.0000, 0.3849, 0.1836, 0.0258, 0.0000, 0.3849, 0.1836, 0.0258,
         0.0000, 0.3849, 0.1836]])


In [23]:
# 산술 연산
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


print(tensor, "\n\n", y1, "\n\n", z1)

tensor([[0.2240, 0.0000, 0.9753, 0.1161],
        [0.3348, 0.0000, 0.0995, 0.0501],
        [0.0473, 0.0000, 0.1144, 0.5100],
        [0.0258, 0.0000, 0.3849, 0.1836]]) 

 tensor([[1.0149, 0.1779, 0.1814, 0.4025],
        [0.1779, 0.1245, 0.0528, 0.0561],
        [0.1814, 0.0528, 0.2754, 0.1389],
        [0.4025, 0.0561, 0.1389, 0.1825]]) 

 tensor([[5.0171e-02, 0.0000e+00, 9.5130e-01, 1.3477e-02],
        [1.1210e-01, 0.0000e+00, 9.9054e-03, 2.5092e-03],
        [2.2406e-03, 0.0000e+00, 1.3090e-02, 2.6006e-01],
        [6.6640e-04, 0.0000e+00, 1.4815e-01, 3.3718e-02]])


In [25]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(3.0659) 3.065906524658203 <class 'float'>
